# Generated by Django 4.2.23 on 2025-06-24 13:27

import datetime

from django.db import migrations, models

import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1), validators=[orders.validators.date_of_birth_validator], verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
