# Generated by Django 4.2.23 on 2025-06-26 05:50

import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Введите дату рождения', null=True, validators=[orders.validators.birth_date_validator], verbose_name='Дата рождения'),
        ),
    ]
