USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
AGE_MAX_VALUE = 120
TITLE_MAX_LENGTH = 200
DESCRIPTION_MAX_LENGTH = 2000
TRIM_LEN = 30
ALLOWED_USERNAME_CHARS = r'\w.@+-'
PATTERN = rf'[^{ALLOWED_USERNAME_CHARS}]'
USERNAME_PATH_PARAM_REGEX = (
    rf'(?P<username>{ALLOWED_USERNAME_CHARS}{{1,{USERNAME_MAX_LENGTH}}})'
)
